### PR TITLE
Update profile page

### PR DESCRIPTION
**Pull request by marwajomaa**
relates #547 , #578

to test it :
disable this `` if (process.env.NODE_ENV === 'production') {``   in ``server/contoller/users/editProfile.js`` line 51

### CODE REVIEW

**Comment by thejoefriel** [comment]
Hey, I've tried to test this doing what you said (I also changed in the email to make sure it sent to me) but can't get the email. I then put a console log in the edit Profile just above where you said and this doesn't get reached. Just checking if there's anything else I'm meant to do?

**Comment by marwajomaa** [comment]
Hi Joe, Thanks for reviewing the pr.
I test that again and logged in as a trainer mark and it's working good, I add in dummy data tow users with officalLocalLead: true, and the emails for me, and I receive the 2 emails as added and removed local lead. if you doing the same thing it should be work I guess :)

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 

> I then put a console log in the edit Profile just above where you said a...

did you do that while `edit` the local lead in the profile page? or while `leave` group?

**Comment by RamyAlshurafa** [comment]
@thejoefriel 
what @marwajomaa worked on is sending the email to local lead when trainers editing the local lead from their profile page,(I've tested it and worked for me).
so I'm going to merge this and please open an issue if you got anything else

**Pull request merged**
